(package "mbs"
         "0.1.0"
         "Minibuffer Stats")

(website-url "https://github.com/jcs-elpa/mbs")
(keywords "convenience" "minibuffer" "stats")

(package-file "mbs.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")
(source "jcs-elpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
